default:
  plugins:
    - image
    - link
    - media

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table | media
  plugins:
    - table
    - media
